spring.datasource.url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
spring.datasource.username: ${USERNAME}
spring.datasource.password: Oradoc_db1
spring.datasource.platform: oracle
spring.datasource.tomcat.driver-class-name: com.oracle.jdbc.OracleDriver

spring.datasource.initialization-mode: always