version: 2.1

orbs:
  nais: navikt/nais-deployment@dev:master

executors:
  openjdk:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/app

jobs:
  install:
    executor: openjdk
    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle build
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  test:
    executor: openjdk
    steps:
      - attach_workspace:
          at: ~/app
      - run: echo "Run some tests..."

  build-and-push-docker-image-to-gpr:
    executor: openjdk
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - nais/docker-deploy:
          image: navikt/infotrygd-maksdato/maksdato
          registry: docker.pkg.github.com

  manual-build-and-push-docker-image-to-gpr:
    executor: openjdk
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ~/app
      - run: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD" docker.pkg.github.com
      - run: |
          IMAGE="docker.pkg.github.com/navikt/infotrygd-maksdato/maksdato:1.2"
          echo $IMAGE
          docker build -t $IMAGE .
          IMAGE_ID=`docker images $IMAGE -q`
          docker push $IMAGE

workflows:
  test-and-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - manual-build-and-push-docker-image-to-gpr:
          requires:
            - test
      
      - nais/deploy:
          build-and-push-docker-image: false
          context: NAIS deployment
          repo: navikt/infotrygd-maksdato
          image: docker.pkg.github.com/navikt/infotrygd-maksdato/maksdato:1.2
          github-app-id: 34242
          nais-template: naisPreprod.yaml
          environment: dev-fss
          team: infotrygd
          filters:
            branches:
              only: master
          requires:
            - manual-build-and-push-docker-image-to-gpr
